#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Config-Any
Version  : 0.32
Release  : 12
URL      : https://cpan.metacpan.org/authors/id/H/HA/HAARG/Config-Any-0.32.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/H/HA/HAARG/Config-Any-0.32.tar.gz
Summary  : Load configuration from different file formats, transparently
Group    : Development/Tools
License  : Artistic-1.0-Perl
BuildRequires : buildreq-cpan
BuildRequires : perl(Module::Pluggable::Object)

%description
NAME
Config::Any - Load configuration from different file formats,
transparently

%package dev
Summary: dev components for the perl-Config-Any package.
Group: Development
Provides: perl-Config-Any-devel = %{version}-%{release}
Requires: perl-Config-Any = %{version}-%{release}

%description dev
dev components for the perl-Config-Any package.


%prep
%setup -q -n Config-Any-0.32

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/Config/Any.pm
/usr/lib/perl5/vendor_perl/5.28.2/Config/Any/Base.pm
/usr/lib/perl5/vendor_perl/5.28.2/Config/Any/General.pm
/usr/lib/perl5/vendor_perl/5.28.2/Config/Any/INI.pm
/usr/lib/perl5/vendor_perl/5.28.2/Config/Any/JSON.pm
/usr/lib/perl5/vendor_perl/5.28.2/Config/Any/Perl.pm
/usr/lib/perl5/vendor_perl/5.28.2/Config/Any/XML.pm
/usr/lib/perl5/vendor_perl/5.28.2/Config/Any/YAML.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Config::Any.3
/usr/share/man/man3/Config::Any::Base.3
/usr/share/man/man3/Config::Any::General.3
/usr/share/man/man3/Config::Any::INI.3
/usr/share/man/man3/Config::Any::JSON.3
/usr/share/man/man3/Config::Any::Perl.3
/usr/share/man/man3/Config::Any::XML.3
/usr/share/man/man3/Config::Any::YAML.3
